services:
  postgres:
    image: postgres:latest
    container_name: container_parking_db
    environment:
      POSTGRES_DB: parkingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: